version: '3.9'

services:

  app1:
    platform: linux/amd64
    image: jorgedevsoftware/rinha-backend-quarkus-2026:3.0
    container_name: rinha-app1
    user: root
    environment:
      LOAD_DATASET: "true"
      DATA_BIN_PATH: "/data/data.bin"
      CENTROIDS_BIN_PATH: "/data/data_centroids.bin"
    volumes:
      - dataset:/data
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "270MB"
    networks:
      - rinha

  app2:
    platform: linux/amd64
    image: jorgedevsoftware/rinha-backend-quarkus-2026:3.0
    container_name: rinha-app2
    environment:
      LOAD_DATASET: "false"
      DATA_BIN_PATH: "/data/data.bin"
      CENTROIDS_BIN_PATH: "/data/data_centroids.bin"
    volumes:
      - dataset:/data
    depends_on:
      app1:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "55MB"
    networks:
      - rinha

  haproxy:
    platform: linux/amd64
    image: haproxy:2.8-alpine
    container_name: rinha-haproxy
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      app1:
        condition: service_started
      app2:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "25MB"
    networks:
      - rinha

volumes:
  dataset:

networks:
  rinha:
    driver: bridge
